name: mini-brimble

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_PATH=/app/data/app.db
      - WORKSPACE_DIR=/app/workspace
      - CADDY_ADMIN_URL=http://caddy:2019
      - BUILDKIT_HOST=docker-container://buildkit
      - DOCKER_NETWORK=mini-brimble_brimble-net
    volumes:
      - ./data:/app/data
      - ./workspace:/app/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - caddy
      - buildkit
    networks:
      - brimble-net

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "2019:2019"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./caddy/caddy.json:/etc/caddy/caddy.json
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - brimble-net
    command: caddy run --config /etc/caddy/caddy.json

  buildkit:
    image: moby/buildkit:latest
    container_name: buildkit
    privileged: true
    networks:
      - brimble-net
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - buildkit_cache:/var/lib/buildkit

networks:
  brimble-net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  buildkit_cache:
